### ISSUE TITLE
Captain's Edition compatibility

### ISSUE THREAD

**Issue by Zehirmahn** [hugomg/ftl-cheatsheet#2]
I find your sheet very well done and useful,
but I am unable to generate a sheet for Captain's Edition mod.

Could you consider adding this feature?
Thanks

**Comment by hugomg** [comment]
I'm glad you found the cheatsheet helpful! Unfortunately, I don't think I can fix that, as I'm busy with other things. On top of that, I've never played that mod...

One tricky bit of the current code is that several parts are hardcoded, such as the species and ship list. To get it to work for a mod, we'd either have to add more hardcoded stuff for the mod, or figure out ways to make such things no longer hardcoded.
